### ISSUE TITLE
Problem with OilLibrary

### ISSUE THREAD

**Issue by lindbergh153** [socolofs/tamoc#15]
Hello developers, 
sorry to bother you. I tried to input the oil substance by using the OilLibrary package and failed. The error message is attached as follows.
==================================================================================
     -->Loading NOAA Oil Library Oil:  AD00709
     -->Record name:  MALONGO
Traceback (most recent call last):
  File "D:/PyOilSpill/test.py", line 35, in <module>
    num_oil_elements, water, current)
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\blowout.py", line 300, in __init__
    self._update()
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\blowout.py", line 321, in _update
    self.q_type)
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\dbm_utilities.py", line 77, in get_oil
    substance
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\dbm_utilities.py", line 578, in load_adios_oil
    vapor_pressure_5C = gnome_oil.vapor_pressure(278.15)  # Pa
TypeError: unhashable type: 'OilProps'

Process finished with exit code 1

**Comment by lindbergh153** [comment]
Thanks for your reply. I ran the code recommended and the error information is attached below. I guess something wrong with the installation.

from tamoc import dbm_utilities as dbm_utils
oil = dbm_utils.get_oil('AD00709', 20000., 2000.)

"D:\Program Files\MiniANACONDA\envs\py376\python.exe" D:/PyOilSpill/test.py
     -->Loading NOAA Oil Library Oil:  AD00709
     -->Record name:  MALONGO
Traceback (most recent call last):
  File "D:/PyOilSpill/test.py", line 5, in <module>
    oil = dbm_utils.get_oil('AD00709', 20000., 2000.)
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\dbm_utilities.py", line 77, in get_oil
    substance
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\dbm_utilities.py", line 578, in load_adios_oil
    vapor_pressure_5C = gnome_oil.vapor_pressure(278.15)  # Pa
TypeError: unhashable type: 'OilProps'

**Comment by ChrisBarker-NOAA** [comment]
Guessing here, but I think the specific issue is that the vapor_pressure method uses an lru_cache.

and the lru_cache requires that the parameters be "hashable", which and oil_props object is not.

However, this has indeed worked in the past, so I think the issue here is that the lru_cache syem is different in some wy depending on Python version, etc.

OilLibrary is best tested with Python 3.8 (and py2.7, bu that's dead now) -- so if TAMOC is py38 compatible, I'd go with that verson and see if you can get it to work.

If not -post an issue on the OilLibary projects as we'll see what we can do:

https://github.com/NOAA-ORR-ERD/OilLibrary

**Comment by ChrisBarker-NOAA** [comment]
NOTE: I looked yesterday, and realized I hadn't pushed the latest version to gitHub. I've now done that, so please get the latest OilLibrary code and try again.

**Comment by lindbergh153** [comment]
I updated the package and the same issue occurred as follows. The python version I used is 3.76. 

from tamoc import dbm_utilities as dbm_utils
oil = dbm_utils.get_oil('AD00709', 20000., 2000.)

     -->Loading NOAA Oil Library Oil:  AD00709
     -->Record name:  MALONGO
Traceback (most recent call last):
  File "<input>", line 1, in <module>
 File "D:\Program Files\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "D:\Program Files\PyCharm Community Edition 2020.3.2\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/PyOilSpill/3D_trajectory/new case.py", line 6, in <module>
    oil = dbm_utils.get_oil('AD00709', 20000., 2000.)
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\dbm_utilities.py", line 77, in get_oil
    substance
  File "D:\Program Files\MiniANACONDA\envs\py376\lib\site-packages\tamoc\dbm_utilities.py", line 578, in load_adios_oil
    vapor_pressure_5C = gnome_oil.vapor_pressure(278.15)  # Pa
TypeError: unhashable type: 'OilProps'

**Comment by ChrisBarker-NOAA** [comment]
Try Python 3.8 -- that may be the issue.
